server:
  port: 8080


spring:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:financial
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update



